GET http://localhost:3000/books HTTP/1.1

##

GET http://localhost:3000/books/1 HTTP/1.1

##

POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
  "nombre": "Una breve historia del tiempo",
  "autor": "Stephen Hawking",
  "año": 1988
}

##

PUT http://localhost:3000/books/3 HTTP/1.1
Content-Type: application/json

{
   "año": 1990
}

##

DELETE http://localhost:3000/books/2 HTTP/1.1